jwt:
  key:
    secret: 123123123123123123123123123123123123123123123123123123123123123213213213123123123123123
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:server
    driver-class-name: org.h2.Driver
    username: one
    password: one

#file:
#  profileImg: ProfileImg/
#  boardImg: BoardImg/
#  itineraryImg: ItineraryImg/

iam:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

env: server
logTracer: false

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    datasource:
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:mem:test
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 21363260622-4pnht3ff0v1t0h4259ue00rpdr733ub9.apps.googleusercontent.com
            clientSecret: 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
            scope: profile, email
